In [1]:
# Do not modify or delete this cell
# Do execute it
# It will enable the only package you are allowed to use in this assignment.
#
import numpy as np
import math
import matplotlib.pyplot as plt

**Some Important Instructions (read carefully)**

When the assignment is complete, make sure you

- fill in code when asked for
- **don't leave any ellipses (...) remaining in your code cells**
- run the entire notebook using *"Restart Kernel and Run All Cells"*
- save the notebook
- submit it 

Make sure that when the entire notebook is run using *"Restart Kernel and Run All Cells"*
no errors are obtained (including one that might be included by me for illustrative purposes). 

If you are asked to create a Python object and assign a name to it
- use that <u>exact</u> name and not modifications of it

If you are presented with a cell with a line with only ellipses i.e. ... that is meant to be a place where you should be putting lines of code. 

If you are presented with a cell looking like this:

    variable name = ...
      
that is meant to be a place where you should be filling in the right hand side of the Python assignment.

**Remove all ellipses when you complete a cell.**

If you are asked to provide the right hand side as a **literal** that means that the right hand side should not include variable names, arithmetic operations, or function evaluations. Here are some examples where the right hand side is a literal:

    x=5 
    y="dog" 
    z=98.6 

and here are examples where the right hand side is <u>not</u> a literal:

    x=np.sqrt(5)
    y="dog"+"cat"
    z=98.6/23.4
    w=x+z

If you are asked to provide the right hand side as a *list of literals*, each of the entries in your list should be a literal.

For problems in this assignment (and in future assignments) you will see cells where I expect you to fill in code or text with commented out lines like this:

"# Code cell for Problem N - do not delete or modify this line"

In which case, you should provide code below that line in the cell and make sure to execute it.

"# Print cell for Problem N. Do not modify this cell. Do execute it."

In this case, you should not modify the cell at all, just execute it (after providing code in the previous cell or cells).

**In future assignments**

You will find occasional code cells with snippets of code that you should not need to modify. There are commented lines indicating this that appear as something like

"# Do not modify code in this cell"

or 

"# Do not modify the following code #"

and at times you will see

"# Do not modify code in the following cell"

Occasionally, you will see a variant of 

"# You might want to try modifying parameters in this code#"

where you are encouraged to modify some aspect of the code to further investigate something.

**Sampling a pair of dependent random variables**

Suppose $X$ and $Y$ have the following joint probability mass function:

$$
\begin{array}{c|ccccc|}
P(X=x,Y=y) & y=0 & y=1 \\ \hline
x=0 & 1/12 & 2/12 \\
x=1 & 6/12 & 3/12 \\
\end{array}
$$

One way to imagine sampling $(X,Y)$ is to think of sampling a random variable $Z$ taking values $0,1,2,$ and 3
according to this probability distribution:

$$
\begin{array}{c|ccccc|}
z & P(Z=z)  \\ \hline
0 & 1/12\\
1 & 2/12 \\
2 & 6/12 \\
3 & 3/12\\
\end{array}
$$

and then depending on what value of $Z$ we get define $(X,Y) = f(Z)$ where $f$ is this function

$$
\begin{array}{c|ccccc|}
z & f(z)  \\ \hline
0 & (0,0)\\
1 & (0,1) \\
2 & (1,0) \\
3 & (1,1)\\
\end{array}
$$

But there is another approach. We can sample $X$ and $Y$ in two steps.

**Step 1** Sample $X$ according to its *marginal* distribution. (Gotten by summing rows in the probability mass function).

$$
\begin{array}{c|ccccc|}
x & P(X=x)  \\ \hline
0 & 3/12\\
1 & 9/12\\
\end{array}
$$

**Step 2** Depending on which value of $X$ we get 

- if $X=0$ sample $Y$ from the conditional distribution of $Y$ given $X=0$

$$
\begin{array}{c|ccccc|}
y & P(Y=y|X=0)  \\ \hline
0 & 1/3\\
1 & 2/3\\
\end{array}
$$

- if $X=1$ sample $Y$ from the conditional distribution of $Y$ given $X=1$

$$
\begin{array}{c|ccccc|}
y & P(Y=y|X=1)  \\ \hline
0 & 2/3\\
1 & 1/3\\
\end{array}
$$

where the conditional distributions are obtained by renormalizing a row by dividing it by its sum.



More generally, given two random variables $X$ and $Y$ each taking a finite number of
possible values, we can represent that distribution using a table:
$$
\begin{array}{c|ccccc|}
P(X=x_i,Y=y_j) & y_0 & y_2 & \cdots & y_{n-1}\\ \hline
x_0 & p_{x_0,y_0} & p_{x_0,y_1} & \cdots & p_{x_0,y_{n-1}} \\
x_1 & p_{x_1,y_0} & p_{x_1,y_1} & \cdots & p_{x_1,y_{n-1}} \\
\vdots & \vdots & \vdots & \vdots & \vdots \\
x_{m-1} & p_{x_{m-1},y_0 }& p_{x_{m-1},y_1} & \cdots & p_{x_{m-1},y_{n-1}} \\
\end{array}
$$

We can sample $(X,Y)$ in two steps. 

**Step 1.** Sample $X$ according to its marginal distribution, which is obtained by computing

 the row sums of the probabilities in the table. 

**Step 2.** Sample $Y$ according to the conditional distribution of $Y$ given the $X$ that was just obtained. This distribution is obtained by dividing the row corresponding to the $X$ obtained by its row sum.

**Sampling multiple dependent random variables - general considerations**

What if we have many dependent random variables? 
What was just described for two random variables generalizes to many random variables.

Given a sequence of *dependent* random variables $X_0,X_1,X_2,$ $\ldots,$ $X_{n-1}$ whose joint distribution is known, if we want to sample these random variable from that joint distribution, we can, in principle, carry out the following sequence of steps

* sample $X_0$ from its marginal distribution,

* sample $X_1$ from the conditional distribution of $X_1$ given $X_0$ takes the value obtained in step 0

* sample $X_2$ from the conditional distribution of $X_2$ given $X_0$ and $X_1$ take the values obtained in the previous steps

* sample $X_3$ from the conditional distribution of $X_3$ given $X_0, X_1$ and $X_2$ take the values obtained in the previous steps,

and so on ... . 

Observe that that in order to carry out this program we would need to be able to get our hands on each conditional distribution of $X_k$ given $X_0,X_1,\ldots,X_{k-1}$ which can become an increasingly complex problem.

**A Simplifying Assumption**

Suppose it is the case that for each $k,$ the conditional distribution of $X_k$ given $X_0,X_1,\ldots,X_{k-1}$ only depends on $X_{k-1}.$ In other words, give the history of what we have seen thus far, to determine the conditional distribution of the next random variable **we only need to know the value of the most recent variable we've seen.** This assumption is referred to as the *Markov assumption*, and assuming we can make this assumption, life becomes far easier. (Of course, in applications, its use can lead to misleading results if this powerful model assumption fails to hold and you pretend it does.) 

**Markov chains:**

Markov chains are special sequences of random variables, used to model systems that move around from state to state according to a very simple rule. Loosely speaking, once the system is in some state, it moves randomly to another state (or stays in its current state) with probabilities that only depend on the current state (how we got to this state has no bearing on the probabilities for the next move).

Formally, a Markov chain with state space $S=\{0,1,...,K-1\}$ is a sequence of random variables $X_0,X_1,X_2,\ldots,X_{n-1},\ldots$ with the following properties:

(a) each $X_{t}$ takes a value in $S$ and

(b) the distribution of $X_{t+1}$ given $X_0,\ldots,X_t$ only depends on the value of $X_t$ for every $t$ i.e.

$$
P[X_{t+1}=j \vert X_0=i_0,X_1=i_1,\ldots,X_t=i_t] = 
P[X_{t+1}=j \vert X_t=i_t].
$$

As a consequence of the above statements, we can introduce a $K \times K$ matrix $Q^{(t)},$ referred to as the  *transition matrix* for the Markov chain **at time $t.$**
The $i,j$ entry in this matrix tell us the conditional probability of $X_{t+1}=j$ (moving to state $j$) given that $X_t = i.$ 

We call the Markov chain *stationary* if the transition matrix is the same for all $t,$ so there is only one transition matrix which we denote by $Q.$ This single matrix can be thought of as giving the *law of motion* of our system under investigation.

Symbolically, if $Q = (q_{i,j})$ so that $q_{i,j}$ denotes the entry in row $i$ and column $j$ of $Q$ and we have

$$
P[X_{t+1}=j \vert X_t = i] = q_{i,j}
$$

This is a lot to take in, and it is best to illustrate with some examples.

**Example 1. The IID case**

For example, if we flip a fair coin repeatedly and can assume that the flips are independent. Let the state 0 refer to tails, and 1 refer to heads and we get this transition matrix
$$
Q = \left[
\begin{array}{cc}
\frac{1}{2} &  \frac{1}{2} \\
\frac{1}{2} &  \frac{1}{2} \\
\end{array}
\right]
$$

Instead, if the coin is biased so that heads occurs 2/3 of the time but the flips are still independent we get this transition matrix

$$
Q = \left[
\begin{array}{cc}
\frac{1}{3} &  \frac{2}{3} \\
\frac{1}{3} &  \frac{2}{3} \\
\end{array}
\right]
$$

More generally, if $X_0,X_1,\ldots,$ are **iid random variables** taking values in $S = \{0,\ldots,K-1\}$ with 
$$
P[X_i = j] = p_j,~\mbox{ for } j=0,\ldots,K-1,
$$
then this defines a Markov chain whose transition matrix is the same in every row. 
$$
Q = \left[
\begin{array}{ccccc}
p_0 & p_1 & \cdots & p_{K-2} & p_{K-1} \\
p_0 & p_1 & \cdots & p_{K-2} & p_{K-1} \\
\vdots & \vdots & \vdots & \vdots & \vdots \\
p_0 & p_1 & \cdots & p_{K-2} & p_{K-1} \\
p_0 & p_1 & \cdots & p_{K-2} & p_{K-1} \\
\end{array}
\right]
$$

The more interesting cases of Markov chains are ones for which the random variables involved are *dependent*.

**Example 2: Controlling the House**

Every 2 years, elections in the U.S. are held and it is determined which of the two parties (R, D) controls the house of representatives. 

Think of the state space as $\{ 0,1\}$ where $0$ refers to D and $1$ refers to R.

- Given that the D party currently controls congress the chance it holds congress the next time around is 30%.

- Given that the R party currently controls congress, the chance it holds congress is 40%.

The transtion matrix then looks like this

$$
Q =
\left[
\begin{array}{cc}
.3 & .7\\
.6 & .4 \\
\end{array}
\right]
$$

It helps to keep in mind that rows refer to the current state and columns to the next state 

$$
\begin{array}{ccc}
& & next state \\
& & D~~~R \\
current state &
\begin{array}{c}
D\\
R
\end{array}
&  
\left[
\begin{array}{cc}
.3 & .7\\
.6 & .4 \\
\end{array}
\right]
\end{array}
$$

so, for example, if the current state is D, the chance of being in state D in the next time step is 30%.


**Example 3. The Gamophobe**

Gamophobia refers to fear of commitment in relationships. A certain unnamed individual (person X) is regularly dating three different potential partners. These partners are very fond of person X (and are infinitely patient!), so whenever asked out on a date, they always say yes. 

Let's refer to these potential partners as 0, 1, and 2. Every time person X 

- goes on a date with person 0, they next 
    - date person 0 with probability $1/6$
    - date person 1 with probability $2/6$ 
    - date person 2 with probability $3/6$
- goes on a date with person 1, they next 
    - date person 0 with probability $1/2$
    - date person 1 with probability $0$ 
    - date person 2 with probability $1/2$
- goes on a date with person 2, they next 
    - date person 0 with probability $1/4$
    - date person 1 with probability $1/4$ 
    - date person 2 with probability $1/2$

This person's sequence of dates then forms a Markov chain with transition matrix

$$
Q = \left[
\begin{array}{ccc}
1/6 &  2/6 & 3/6 \\
1/2 &  0 & 1/2  \\
1/4 & 1/4 & 1/2 \\
\end{array}
\right]
$$

Here, we see that conditioning on $X_t$ the distribution of $X_{t+1}$ 
differs depending on the value of $X_t$ i.e. the random variables $X_t$ and $X_{t+1}$ are *dependent.* 

**Example 4: Random Walk with Reflecting Boundary - version 1**

In the typical *symmetric random walk* on the integers, starting in position $i,$ in each step we move either to the left or to the right by 1 unit each with probability 1/2.

If we take our state space to be the finite set $\{0,1,\ldots,K-1\}$ with $K\geq 4$ then 

- if our starting position is in $\{ 1,2,\ldots,K-2\}$ we move one step to the left or right, each with probability 1/2.
- if our starting position is 0 we can't move to the left so we always move to state 1, and 
- if our starting position is $K-1$ we can't move to the right, so we always move to state $K-2.$

If $K=5$ our transition matrix looks like this

$$
\begin{array}{cc}
 & 0~~~~~~1~~~~~~2~~~~~3~~~~~~4 \\
\begin{array}{c}
0\\
1\\
2\\
3\\
4\\
\end{array}
& \left[
\begin{array}{cccccc}
0 & 1 & 0 & 0 & 0\\
\frac{1}{2} & 0 & \frac{1}{2} & 0 & 0\\
0 & \frac{1}{2} & 0 & \frac{1}{2} & 0 \\
0 & 0 & \frac{1}{2} & 0 & \frac{1}{2}\\
0 & 0 & 0 & 1 & 0\\
\end{array}
\right]
\end{array}
$$




for example, if we are currently in state 0 we move to state 1 in the next time step with probability 1. If we are in state 1, we move to either state 0 or state 2 each with probability $\frac{1}{2}.$

**Example 5: Random Walk with Reflecting Boundary - version 2**

Another variation on the above example is one where, when we are in state 0 we either stay there, or move to state 1 each with probability $\frac{1}{2}$, and similarly, if we are in state $K-1$ we either stay there or we move to state $K-2$ again with equal probability.

For example, if $K=5$ our transition matrix looks like this

$$
\begin{array}{cc}
 & 0~~~~~~1~~~~~~2~~~~~3~~~~~~4 \\
\begin{array}{c}
0\\
1\\
2\\
3\\
4\\
\end{array}
& \left[
\begin{array}{cccccc}
\frac{1}{2} & \frac{1}{2} & 0 & 0 & 0\\
\frac{1}{2} & 0 & \frac{1}{2} & 0 & 0\\
0 & \frac{1}{2} & 0 & \frac{1}{2} & 0 \\
0 & 0 & \frac{1}{2} & 0 & \frac{1}{2}\\
0 & 0 & 0 & \frac{1}{2} & \frac{1}{2}\\
\end{array}
\right]
\end{array}
$$


**Transition Matrices are Stochastic Matrices**

A *stochastic matrix* is a matrix all of whose entries are nonnegative and whose rows sum to 1. Since a row of a transition matrix gives a conditional probability distribution, that row has nonnegative entries summing to 1, so a transition matrix is always a stochastic matrix.

There is also the notion of a *doubly stochastic* matrix, whose entries are all nonnegative and whose rows *and* columns all sum to 1. A transition matrix need not be doubly stochastic as demonstrated in the Political Party in Control example.

**One-Step Distributions**

Suppose at time $t$ we know the probability distribution of $X_t,$ say we define
$$
\pi_i = P[X_t = i],~\mbox{ for}  ~i=0,1,\ldots,K-1.
$$

What is the probability distribution of $X_{t+1}$? 
In other words, if we define 

$$
\tilde{\pi}_j := P[X_{t+1}=j],~ \mbox{ for } j=0,1,\ldots,K-1
$$

how can we calculate these values?

We can answer using the law of total probability and the definition of conditional probability to write this as

$$
\tilde{\pi}_j = P[X_{t+1}=j] = \sum_{i=0}^{K-1} P[X_{t+1}=j, X_{t}=i]
$$
$$
= \sum_{i=0}^{K-1} P[X_{t+1}=j \vert X_{t}=i] P[X_t = i]
$$
$$
= \sum_{i=0}^{K-1} \pi_i q_{ij}.
$$

If this reminds you of multiplication of a matrix and a vector, your intuition is correct. Let's define row vectors

$$
\pi = [ \pi_0,\ldots,\pi_{K-1}]
$$

and

$$
\tilde{\pi} = [ \tilde{\pi_0},\ldots,\tilde{\pi}_{K-1}]
$$

then the above equation says that

$$
\tilde{\pi} = \pi Q.
$$


**Problem 1 (25 points)** 

Consider the Markov chain on the discrete circle, with some **odd** positive integer value of $N \geq 3$ and assume that, given at time $t$ if the chain is in state $i,$ at time $t+1$ the chain is in state

$$
\left\{ \begin{array}{ll}
i+1 & \mbox{ with probability } 
\frac{1}{2} A_t \left(1-\frac{4\phi_N(i)}{(N-1)^2}\right) \\
i-1 & \mbox{ with probability } 
\frac{1}{4}A_t \left(1-\frac{4\phi_N(i)}{(N-1)^2}\right) _N\\
i & \mbox{ with probability } 1 - \frac{3}{4}A_t \left(1-\frac{4\phi_N(i)}{(N-1)^2}\right) \\
\end{array}
\right.
$$

where $\phi_N(i)$ denotes distance, in terms of states, from $i$ to 0 i.e.

$$
\phi_N(i) = \left\{ \begin{array}{ll}
i & \mbox{ if } 0 \leq i \leq (N-1)/2\\ 
N-i & \mbox{ if } (N+1)/2 \leq i \leq N-1\\
\end{array}
\right.
$$

and where 

$$
A_t = \frac{1+\log(t+2)}{2+\log(t+2)}.
$$

In the following code cell, write a **completely self-contained** function called **transition_matrix1** that takes as input 

- a value of $t$ (a nonnegative integer) 
- a value of $N$ (an odd integer $\geq 3$)

and outputs

- the transition matrix $Q^{(t)}$ for the Markov chain at time $t$ (as a $N \times N$ numpy 2d array) so that the $i,j$ entry is

$$
P[X_{t+1}=j \vert X_t = i] 
$$

for $i,j=0,\ldots,N-1.$

Here, **completely self-contained means that any user-defined auxilliary functions or variables appearing that are not function arguments in your function should be defined in the body of the code**. This does not include numpy functions and constants. You can use those in the body of your code if you need them.

In [2]:
# Code cell for Problem 1 - do not delete or modify this line
def transition_matrix1(N, t):
    def phi(i):
        if 0 <= i <= (N - 1) / 2:
            return i
        elif (N + 1) / 2 <= i <= N - 1:
            return N - i
    def A(t):
        return (1 + np.log(t + 2)) / (2 + np.log(t + 2))
    Q = np.zeros((N, N))
    for i in range(N):
        piplus1 = 0.5 * A(t) * (1 - 4 * phi(i) / ((N - 1) ** 2))
        piminus1 = 0.25 * A(t) * (1 - 4 * phi(i) / ((N - 1) ** 2))
        pi = 1 - 0.75 * A(t) * (1 - 4 * phi(i) / ((N - 1) ** 2))
        Q[i][(i + 1) % N] = piplus1
        Q[i][i] = pi
        Q[i][(i - 1) % N] = piminus1
    return Q

In [3]:
# Print cell1  for Problem 1 - do not delete or modify this line
# Do execute this cell.
print(transition_matrix1(5,1).round(3))

[[0.492 0.339 0.    0.    0.169]
 [0.127 0.619 0.254 0.    0.   ]
 [0.    0.085 0.746 0.169 0.   ]
 [0.    0.    0.085 0.746 0.169]
 [0.254 0.    0.    0.127 0.619]]


In [4]:
# Print cell2  for Problem 1 - do not delete or modify this line
# Do execute this cell.
print(transition_matrix1(5,2).round(3))

[[0.471 0.352 0.    0.    0.176]
 [0.132 0.604 0.264 0.    0.   ]
 [0.    0.088 0.736 0.176 0.   ]
 [0.    0.    0.088 0.736 0.176]
 [0.264 0.    0.    0.132 0.604]]


In [5]:
# Print cell3  for Problem 1 - do not delete or modify this line
# Do execute this cell.
print(transition_matrix1(5,3).round(3))

[[0.458 0.361 0.    0.    0.181]
 [0.136 0.593 0.271 0.    0.   ]
 [0.    0.09  0.729 0.181 0.   ]
 [0.    0.    0.09  0.729 0.181]
 [0.271 0.    0.    0.136 0.593]]


In [6]:
# Print cell3  for Problem 1 - do not delete or modify this line
# Do execute this cell.
print(transition_matrix1(5,1000).round(3))

[[0.334 0.444 0.    0.    0.222]
 [0.166 0.501 0.333 0.    0.   ]
 [0.    0.111 0.667 0.222 0.   ]
 [0.    0.    0.111 0.667 0.222]
 [0.333 0.    0.    0.166 0.501]]


**Problem 2 (5 points) **

For the Markov chain defined in Problem 1, suppose the chain is in state 0 at time 0.
Find the probability distribution of the position at time $t=10.$
In the code cell below, you should assign your answer to a 1-d array called **position_distribution2**.

Use the following code cell to compute the answer.

In [7]:
# Code cell for Problem 2 - do not delete or modify this line
#Assumed N = 5
def positiondistribution(N, t):
    pi = np.zeros(N)
    pi[0] = 1
    for i in range(t):
        Q = transition_matrix1(N, i)
        pi = pi.dot(Q)
    return pi
position_distribution2 = positiondistribution(5, 10)

In [8]:
# Print cell for Problem 2 - Do not modify this cell. Do execute this cell.
print(position_distribution2.round(3))

[0.129 0.195 0.286 0.237 0.154]


**Problem 3 (5 points)**

Assume that for the Markov chain in Problem 1 all states are equally likely for the position at time 0.
Find the probability distribution of the position at time $t=10.$
In the code cell below, you should assign your answer to a **1-d array** called **position_distribution3**.

Use the following code cell to compute the answer.

In [9]:
# Code cell for Problem 3 - do not delete or modify this line
def positiondistribution(N, t):
    pi = np.full(N, 1/N)
    for i in range(t):
        Q = transition_matrix1(N, i)
        pi = pi.dot(Q)
    return pi
position_distribution3 = positiondistribution(5, 10)

In [10]:
# Print cell for Problem 3 - Do not modify this cell. Do execute this cell.
print(position_distribution3.round(3))

[0.13  0.178 0.265 0.257 0.171]


**Problem 4 (5 points)**

Write a function called **generate_sample_path** that takes as inputs

- $N$ the positive integer definng a discretized circle
- $I$ a starting position for a Markov chain defined in Problem 1
- $T$ a positive integer

and gives as output

- a list giving a simulated sequence of positions $X_0,X_1,\ldots,X_T$ for the Markov chain in Problem 1 starting in position $I$ at time 0. Your positions should be **integers**.

You may use numpy functions in your code. You may also use the function **transition_matrix1** you defined in Problem 1.

Use the following code cell for your code. 

In [11]:
# Code cell for Problem 4 - do not modify or delete this line
def generate_sample_path(N,I,T):
    sample = [I]
    for i in range(T):
        Q = transition_matrix1(N,i)
        next = np.random.choice(range(N), p = Q[sample[-1]])
        sample.append(next)
    return sample

In [12]:
# Test cell for Problem 4 - do not modify or delete this cell
# Do execute it.
path = generate_sample_path(5,0,1000)
print(path)

[0, 0, 0, 1, 1, 2, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 3, 3, 4, 4, 0, 1, 1, 0, 1, 2, 2, 2, 2, 2, 2, 3, 3, 4, 3, 3, 3, 2, 2, 2, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 0, 1, 1, 1, 1, 2, 2, 2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 1, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 0, 0, 0, 4, 0, 1, 2, 3, 2, 2, 2, 2, 2, 3, 4, 0, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 0, 0, 0, 1, 0, 1, 0, 4, 4, 3, 4, 3, 4, 4, 0, 1, 1, 2, 2, 1, 0, 0, 0, 1, 1, 2, 3, 3, 3, 3, 4, 4, 0, 1, 1, 1, 2, 2, 2, 2, 3, 4, 3, 3, 3, 4, 4, 3, 3, 4, 4, 4, 0, 0, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 3, 3, 4, 4, 0, 1, 1, 1, 1, 0, 1, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 3, 4, 0, 0, 0, 4, 4, 0, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 3, 4, 4, 4, 4, 4, 0, 0, 1, 2, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 0, 4, 3, 3, 3, 4, 0, 0, 0, 4, 0, 1, 1, 2, 2, 3, 4, 4, 0, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 3, 4, 4, 4, 0, 1, 2, 2, 3, 

**Problem 5 (25 points)**

If our process in the discretized circle starts at position i and in one step ends at position i+1, 
we call this a *positive step* and if it ends up in position $i-1$ we call this a negative step.

If our process starts at position zero at some time $t$ and is in position zero at a later time $t+k$ with no visits to zero in between, we say that 

- a *counterclockwise wrapping* has occured from time $t$ to time $t+k$ occurs if
    - the process is never in position 0 at times $t+1,\ldots,t+k-1,$ and 
    - the number of positive steps minus the number of negative steps taken at times $t,t+1,\ldots,t+k-1$
is $N,$ 

- a *clockwise wrapping* has occured from time $t$ to time $t+k$ occurs if
    - the process is never in position 0 at times $t+1,\ldots,t+k-1,$ and 
    - the number of positive steps minus the number of negative steps taken at times $t,t+1,\ldots,t+k-1$
is $-N,$ 

- no wrapping has occured from time $t$ to time $t+k$ occurs if
    - the process is never in position 0 at times $t+1,\ldots,t+k-1,$ and 
    - the number of positive steps minus the number of negative steps taken at times $t,t+1,\ldots,t+k-1$
is $0.$

Note that if the process is in position 0 at time $t$ and at time $t+1$ then no wrapping occurs from time $t$ to $t+1.$

We defined the *total number of wrappings* from time 0 to time $T$ to be the number of counterclockwise wrappings minus the number of clockwise wrappings that took place from time 0 to time $T.$

Here is an example of a sequence of positions with $N=5.$

$$
0,1,2,3,2,3,2,2,3,3,4,0,4,0,0,4,3,4,0,1,2,2,2,1,1,0,1,0,1,0,4,3,2,2,3,4,0,0,4,3,2,2,3,2,1,0,1,2
$$

The times at which we visit 0 with no visits to 0 in between are:

$$
t=0,11,13,14,18,25,27,29,36,37,45,50
$$

- Time 0 to time 11 is a counterclockwise wrapping
- Time 11 to time 13 is not a wrapping
- Time 13 to time 14 is not a wrapping
- Time 14 to time 18 is not a wrapping
- Time 18 to time 25 is not a wrapping 
- Time 25 to 27 is not a wrapping
- Time 27 to 29 is not a wrapping
- Time 29 to 36 is not a wrapping
- Time 36 to 37 is not a wrapping
- Time 37 to 45 is clockwise wrapping
- Time 45 to 50 is a counterclockwise wrapping

and the total number of wrappings is 2-1=1.

Write a function called **count_wrappings** that takes as input 

- $N$ the positive integer that determines the discretized circle, and 
- $L$ a **list** of integer positions starting in position 0 at time 0 and computes the total number of wrappings that occur from time 0 to time $T$ equal to the length of the list minus 1. You should assume tha the list contains only allowable moves that our Markov chain on the discretized circle can make, i.e. from position $i$ we can only be in position to $i-1,i$ or $i+1$ (modulo $N$) in the next step.

and outputs

- the number of wrappings that occur (the number of counterclockwise wrappings minus the number of clockwise wrappings)

Your function should be **fully self-contained**. Any auxilliary functions you define to be used by your function **should be defined in the body of your function.**

In [13]:
# Code cell for Problem 5 - do not delete or modify this line
def count_wrappings(N, L):
    counterclockwise, clockwise = 0, 0
    def step(a, b):
        if a == (b + 1) % N:
            return 1
        elif a == (b - 1) % N:
            return -1
        else:
            return 0
    zeros = []
    for i in range(len(L) - 1):
        if L[i] == 0:
            zeros.append(i)
    for j in range(len(zeros) - 1):
        count = []
        start, end = zeros[j], zeros[j + 1]
        for p in range(start, end):
            count.append(step(L[p + 1], L[p]))
        difference = sum(count)
        if difference == N:
            counterclockwise += 1
        elif difference == -N:
            clockwise += 1
    return counterclockwise - clockwise

In [14]:
# Test cell1 for Problem 5 - do not modify this cell
# Do execute it
L=[0,1,2,3,2,3,2,2,3,3,4,0,4,0,0,4,3,4,0,1,2,2,2,1,1,0,1,0,1,0,4,3,2,2,3,4,0,0,4,3,2,2,3,2,1,0,1,2,3,4,0,1]
count_wrappings(5,L)

1

In [15]:
# Test cell2 for Problem 5 - do not modify this cell
# Do execute it
L=[0, 4, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 4, 0, 1, 2, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 4, 0, 0, 0, 0, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 4, 0, 0, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 0, 0, 0, 4, 0, 4, 3, 4, 0, 1, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 0, 0, 4, 0, 4, 4, 4, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 2, 3, 4, 0, 1, 1, 1, 0, 0, 0, 4, 0, 0, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 0, 1, 1, 2, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 3, 3, 3, 2, 1, 1, 1, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 0, 4, 4, 4, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 4, 0, 4, 3, 3, 3, 3, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 3, 4, 0, 4, 0, 0, 0, 0, 0, 1, 1, 1, 0, 4, 4, 4, 0, 1, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 4, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 3, 2, 2, 2, 2, 2, 2, 1, 1, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 0, 1, 1, 1, 0, 0, 4, 4, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 4, 4, 4, 4, 4, 4, 0, 0, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 3, 4, 4, 0, 4, 4, 0, 1, 0, 0, 1, 2, 2, 2, 2, 1, 2, 2, 2, 3, 4, 4, 0, 1, 1, 1, 0, 4, 4, 0, 4, 4, 4, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 3, 4, 0, 4, 4, 3, 3, 4, 0, 1, 1, 0, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 0, 0, 4, 3, 2, 1, 1, 0, 0, 4, 3, 3, 4, 3, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 0, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 0, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 0, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 4, 0, 1, 1, 1, 2, 1, 2, 2, 1, 0, 0, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 4, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 3, 3, 4, 4, 4, 0, 1, 1, 1, 1, 1, 2, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 3, 4, 0, 0, 4, 3, 3, 3, 3, 3, 3, 4, 4, 0, 4, 0, 4, 0, 0, 0, 4, 3, 3, 3, 4, 0, 0, 1, 0, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 3, 4, 0, 0, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3, 4, 0, 1, 0, 1, 0, 4, 0, 1, 2, 3, 2, 2, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 4, 4, 4, 0, 1, 2, 2, 1, 1, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 4, 0, 1, 1, 1, 0, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 3, 3, 3, 3, 4, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2]
count_wrappings(5,L)

26

**Problem 6 (10 points)**

For the Markov chain in Problem 1 starting at position 0, let $X$ denote the number of wrappings that occur from time 0 to time 100. Use Monte-Carlo simulation with a Monte-Carlo sample size of n=1,000 to  

- estimate $\mu=E[X]$ 
- estimate $\sigma = \sqrt{\mbox{Var}(X)}$ 
- estimate the standard error $\mbox{SE}(\hat{\mu}) = \sigma/\sqrt{n}$ of $\hat{\mu},$ and
- get approximate 95% confidence interval $(\mu_L,\mu_U)$ for $\mu.$ 

Assign 

- your estimate of $\mu$ to a variable called **muhat**,
- your estimate of $\sigma$ to a variable called **sigmahat.**
- your estimate of $\mbox{SE}(\hat{\mu})$ to a variable called **SE**
- your lower confidence bound $\mu_L$ to a variable called **muLOWER**
- your upper confidence bound $\mu_U$ to a variable called **muUPPER**



Use the following cell for your code.

In [16]:
# Code cell for Problem 6 - do not modify this line
MC = []
for i in range(1000):
    path = generate_sample_path(5,0,100)
    MC.append(count_wrappings(5, path))
muhat = np.mean(MC)
sigmahat = np.std(MC)
SE = sigmahat / np.sqrt(1000)
z = 1.96 # derived from 95% confidence for a normal distribution
muLOWER = muhat - z * SE
muUPPER = muhat + z * SE

In [17]:
# Print cell for problem 6 - do not modify or delete this cell
# Do execute it
print(muhat)
print(sigmahat)
print(SE)
print(muLOWER)
print(muUPPER)

2.39
1.2007914056987583
0.037972358367633685
2.315574177599438
2.464425822400562


**Important**

- Make sure you run all cells in the notebook in order and no errors occur
- Save your notebook after you run it
- Submit it in Canvas